version: '3.9'
services:
  web:
    build: .
    ports:
      - "9000:9000"
  db:
    image: "postgres"
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: postgres
      POSTGRES_HOST: db
    ports:
      - 5432:5432